In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Auto.csv')
print(dataset)

      mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70
1    15.0          8         350.0        165    3693          11.5    70
2    18.0          8         318.0        150    3436          11.0    70
3    16.0          8         304.0        150    3433          12.0    70
4    17.0          8         302.0        140    3449          10.5    70
..    ...        ...           ...        ...     ...           ...   ...
392  27.0          4         140.0         86    2790          15.6    82
393  44.0          4          97.0         52    2130          24.6    82
394  32.0          4         135.0         84    2295          11.6    82
395  28.0          4         120.0         79    2625          18.6    82
396  31.0          4         119.0         82    2720          19.4    82

     origin                       name
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
392       1            ford mustang gl
393       2                  vw pickup
394       1              dodge rampage
395       1                ford ranger
396       1                 chevy s-10

[397 rows x 9 columns]

In [ ]:
dataset.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [ ]:
dataset.describe()

,mpg,cylinders,displacement,weight,acceleration,year,origin
count,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000
mean,23.515869,5.458438,193.532746,2970.261965,15.555668,75.994962,1.574307
std,7.825804,1.701577,104.379583,847.904119,2.749995,3.690005,0.802549
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.000000,2223.000000,13.800000,73.000000,1.000000
50%,23.000000,4.000000,146.000000,2800.000000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3609.000000,17.100000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [ ]:
dataset.isnull()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
392,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False

In [ ]:
dataset=dataset.drop_duplicates()
print(dataset)

      mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70
1    15.0          8         350.0        165    3693          11.5    70
2    18.0          8         318.0        150    3436          11.0    70
3    16.0          8         304.0        150    3433          12.0    70
4    17.0          8         302.0        140    3449          10.5    70
..    ...        ...           ...        ...     ...           ...   ...
392  27.0          4         140.0         86    2790          15.6    82
393  44.0          4          97.0         52    2130          24.6    82
394  32.0          4         135.0         84    2295          11.6    82
395  28.0          4         120.0         79    2625          18.6    82
396  31.0          4         119.0         82    2720          19.4    82

     origin                       name
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
392       1            ford mustang gl
393       2                  vw pickup
394       1              dodge rampage
395       1                ford ranger
396       1                 chevy s-10

[397 rows x 9 columns]

In [ ]:
dataset.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
year            0
origin          0
name            0
dtype: int64

In [ ]:
dataset.dropna(how='any', subset=['horsepower', 'name'], inplace=True)
print(dataset)

      mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70
1    15.0          8         350.0        165    3693          11.5    70
2    18.0          8         318.0        150    3436          11.0    70
3    16.0          8         304.0        150    3433          12.0    70
4    17.0          8         302.0        140    3449          10.5    70
..    ...        ...           ...        ...     ...           ...   ...
392  27.0          4         140.0         86    2790          15.6    82
393  44.0          4          97.0         52    2130          24.6    82
394  32.0          4         135.0         84    2295          11.6    82
395  28.0          4         120.0         79    2625          18.6    82
396  31.0          4         119.0         82    2720          19.4    82

     origin                       name
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
392       1            ford mustang gl
393       2                  vw pickup
394       1              dodge rampage
395       1                ford ranger
396       1                 chevy s-10

[397 rows x 9 columns]

In [ ]:
X=dataset[['mpg', 'horsepower', 'acceleration']].values
Y=dataset['year'].values
print(X)

[[18.0 '130' 12.0]
 [15.0 '165' 11.5]
 [18.0 '150' 11.0]
 ...
 [32.0 '84' 11.6]
 [28.0 '79' 18.6]
 [31.0 '82' 19.4]]

In [ ]:
from sklearn.impute import SimpleImputer
help(SimpleImputer)
print(X[:, 1:3])

Help on class SimpleImputer in module sklearn.impute._base:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)
 |
 |  Imputation transformer for completing missing values.
 |
 |  Read more in the :ref:`User Guide <impute>`.
 |
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan or None, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_values`
 |      should be set to `np.nan`, since `pd.NA` will be converted to `np.nan`.
 |
 |  strategy : str, default='mean'
 |      The imputation strategy.
 |
 |      - If "mean", then replace missing values using the mean along
 |        each column. Can only be used with numeric data.
 |      - If "median", then replace missing values using the median along
 |        each column. Can only be used with numeric data.
 |      - If "most_frequent", then replace missing using the most frequent
 |        value along each column. Can be used with strings or numeric data.
 |        If there is more than one such value, only the smallest is returned.
 |      - If "constant", then replace missing values with fill_value. Can be
 |        used with strings or numeric data.
 |
 |      .. versionadded:: 0.20
 |         strategy="constant" for fixed value imputation.
 |
 |  fill_value : str or numerical value, default=None
 |      When strategy == "constant", fill_value is used to replace all
 |      occurrences of missing_values.
 |      If left to the default, fill_value will be 0 when imputing numerical
 |      data and "missing_value" for strings or object data types.
 |
 |  verbose : int, default=0
 |      Controls the verbosity of the imputer.
 |
 |  copy : bool, default=True
 |      If True, a copy of `X` will be created. If False, imputation will
 |      be done in-place whenever possible. Note that, in the following cases,
 |      a new copy will always be made, even if `copy=False`:
 |
 |      - If `X` is not an array of floating values;
 |      - If `X` is encoded as a CSR matrix;
 |      - If `add_indicator=True`.
 |
 |  add_indicator : bool, default=False
 |      If True, a :class:`MissingIndicator` transform will stack onto output
 |      of the imputer's transform. This allows a predictive estimator
 |      to account for missingness despite imputation. If a feature has no
 |      missing values at fit/train time, the feature won't appear on
 |      the missing indicator even if there are missing values at
 |      transform/test time.
 |
 |  Attributes
 |  ----------
 |  statistics_ : array of shape (n_features,)
 |      The imputation fill value for each feature.
 |      Computing statistics can result in `np.nan` values.
 |      During :meth:`transform`, features corresponding to `np.nan`
 |      statistics will be discarded.
 |
 |  indicator_ : :class:`~sklearn.impute.MissingIndicator`
 |      Indicator used to add binary indicators for missing values.
 |      `None` if `add_indicator=False`.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  See Also
 |  --------
 |  IterativeImputer : Multivariate imputation of missing values.
 |
 |  Notes
 |  -----
 |  Columns which only contained missing values at :meth:`fit` are discarded
 |  upon :meth:`transform` if strategy is not `"constant"`.
 |
 |  Examples
 |  --------
 |  >>> import numpy as np
 |  >>> from sklearn.impute import SimpleImputer
 |  >>> imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
 |  >>> imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
 |  SimpleImputer()
 |  >>> X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
 |  >>> print(imp_mean.transform(X))
 |  [[ 7.   2.   3. ]
 |   [ 4.   3.5  6. ]
 |   [10.   3.5  9. ]]
 |
 |  Method resolution order:
 |      SimpleImputer
 |      _BaseImputer
 |      sklearn.base.TransformerMixin
 |      sklearn.base.BaseEstimator
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y=None)
 |      Fit the imputer on `X`.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape (n_samples, n_features)
 |          Input data, where `n_samples` is the number of samples and
 |          `n_features` is the number of features.
 |
 |      y : Ignored
 |          Not used, present here for API consistency by convention.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted estimator.
 |
 |  inverse_transform(self, X)
 |      Convert the data back to the original representation.
 |
 |      Inverts the `transform` operation performed on an array.
 |      This operation can only be performed after :class:`SimpleImputer` is
 |      instantiated with `add_indicator=True`.
 |
 |      Note that `inverse_transform` can only invert the transform in
 |      features that have binary indicators for missing values. If a feature
 |      has no missing values at `fit` time, the feature won't have a binary
 |      indicator, and the imputation done at `transform` time won't be
 |      inverted.
 |
 |      .. versionadded:: 0.24
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape                 (n_samples, n_features + n_features_missing_indicator)
 |          The imputed data to be reverted to original data. It has to be
 |          an augmented array of imputed data and the missing indicator mask.
 |
 |      Returns
 |      -------
 |      X_original : ndarray of shape (n_samples, n_features)
 |          The original `X` with missing values as it was prior
 |          to imputation.
 |
 |  transform(self, X)
 |      Impute all missing values in `X`.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape (n_samples, n_features)
 |          The input data to complete.
 |
 |      Returns
 |      -------
 |      X_imputed : {ndarray, sparse matrix} of shape                 (n_samples, n_features_out)
 |          `X` with imputed values.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.TransformerMixin:
 |
 |  fit_transform(self, X, y=None, **fit_params)
 |      Fit to data, then transform it.
 |
 |      Fits transformer to `X` and `y` with optional parameters `fit_params`
 |      and returns a transformed version of `X`.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Input samples.
 |
 |      y :  array-like of shape (n_samples,) or (n_samples, n_outputs),                 default=None
 |          Target values (None for unsupervised transformations).
 |
 |      **fit_params : dict
 |          Additional fit parameters.
 |
 |      Returns
 |      -------
 |      X_new : ndarray array of shape (n_samples, n_features_new)
 |          Transformed array.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.TransformerMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.

[['130' 12.0]
 ['165' 11.5]
 ['150' 11.0]
 ['150' 12.0]
 ['140' 10.5]
 ['198' 10.0]
 ['220' 9.0]
 ['215' 8.5]
 ['225' 10.0]
 ['190' 8.5]
 ['170' 10.0]
 ['160' 8.0]
 ['150' 9.5]
 ['225' 10.0]
 ['95' 15.0]
 ['95' 15.5]
 ['97' 15.5]
 ['85' 16.0]
 ['88' 14.5]
 ['46' 20.5]
 ['87' 17.5]
 ['90' 14.5]
 ['95' 17.5]
 ['113' 12.5]
 ['90' 15.0]
 ['215' 14.0]
 ['200' 15.0]
 ['210' 13.5]
 ['193' 18.5]
 ['88' 14.5]
 ['90' 15.5]
 ['95' 14.0]
 ['?' 19.0]
 ['100' 13.0]
 ['105' 15.5]
 ['100' 15.5]
 ['88' 15.5]
 ['100' 15.5]
 ['165' 12.0]
 ['175' 11.5]
 ['153' 13.5]
 ['150' 13.0]
 ['180' 11.5]
 ['170' 12.0]
 ['175' 12.0]
 ['110' 13.5]
 ['72' 19.0]
 ['100' 15.0]
 ['88' 14.5]
 ['86' 14.0]
 ['90' 14.0]
 ['70' 19.5]
 ['76' 14.5]
 ['65' 19.0]
 ['69' 18.0]
 ['60' 19.0]
 ['70' 20.5]
 ['95' 15.5]
 ['80' 17.0]
 ['54' 23.5]
 ['90' 19.5]
 ['86' 16.5]
 ['165' 12.0]
 ['175' 12.0]
 ['150' 13.5]
 ['153' 13.0]
 ['150' 11.5]
 ['208' 11.0]
 ['155' 13.5]
 ['160' 13.5]
 ['190' 12.5]
 ['97' 13.5]
 ['150' 12.5]
 ['130' 14.0]
 ['140' 16.0]
 ['150' 14.0]
 ['112' 14.5]
 ['76' 18.0]
 ['87' 19.5]
 ['69' 18.0]
 ['86' 16.0]
 ['92' 17.0]
 ['97' 14.5]
 ['80' 15.0]
 ['88' 16.5]
 ['175' 13.0]
 ['150' 11.5]
 ['145' 13.0]
 ['137' 14.5]
 ['150' 12.5]
 ['198' 11.5]
 ['150' 12.0]
 ['158' 13.0]
 ['150' 14.5]
 ['215' 11.0]
 ['225' 11.0]
 ['175' 11.0]
 ['105' 16.5]
 ['100' 18.0]
 ['100' 16.0]
 ['88' 16.5]
 ['95' 16.0]
 ['46' 21.0]
 ['150' 14.0]
 ['167' 12.5]
 ['170' 13.0]
 ['180' 12.5]
 ['100' 15.0]
 ['88' 19.0]
 ['72' 19.5]
 ['94' 16.5]
 ['90' 13.5]
 ['85' 18.5]
 ['107' 14.0]
 ['90' 15.5]
 ['145' 13.0]
 ['230' 9.5]
 ['49' 19.5]
 ['75' 15.5]
 ['91' 14.0]
 ['112' 15.5]
 ['150' 11.0]
 ['110' 14.0]
 ['122' 13.5]
 ['180' 11.0]
 ['95' 16.5]
 ['?' 17.0]
 ['100' 16.0]
 ['100' 17.0]
 ['67' 19.0]
 ['80' 16.5]
 ['65' 21.0]
 ['75' 17.0]
 ['100' 17.0]
 ['110' 18.0]
 ['105' 16.5]
 ['140' 14.0]
 ['150' 14.5]
 ['150' 13.5]
 ['140' 16.0]
 ['150' 15.5]
 ['83' 16.5]
 ['67' 15.5]
 ['78' 14.5]
 ['52' 16.5]
 ['61' 19.0]
 ['75' 14.5]
 ['75' 15.5]
 ['75' 14.0]
 ['97' 15.0]
 ['93' 15.5]
 ['67' 16.0]
 ['95' 16.0]
 ['105' 16.0]
 ['72' 21.0]
 ['72' 19.5]
 ['170' 11.5]
 ['145' 14.0]
 ['150' 14.5]
 ['148' 13.5]
 ['110' 21.0]
 ['105' 18.5]
 ['110' 19.0]
 ['95' 19.0]
 ['110' 15.0]
 ['110' 13.5]
 ['129' 12.0]
 ['75' 16.0]
 ['83' 17.0]
 ['100' 16.0]
 ['78' 18.5]
 ['96' 13.5]
 ['71' 16.5]
 ['97' 17.0]
 ['97' 14.5]
 ['70' 14.0]
 ['90' 17.0]
 ['95' 15.0]
 ['88' 17.0]
 ['98' 14.5]
 ['115' 13.5]
 ['53' 17.5]
 ['86' 15.5]
 ['81' 16.9]
 ['92' 14.9]
 ['79' 17.7]
 ['83' 15.3]
 ['140' 13.0]
 ['150' 13.0]
 ['120' 13.9]
 ['152' 12.8]
 ['100' 15.4]
 ['105' 14.5]
 ['81' 17.6]
 ['90' 17.6]
 ['52' 22.2]
 ['60' 22.1]
 ['70' 14.2]
 ['53' 17.4]
 ['100' 17.7]
 ['78' 21.0]
 ['110' 16.2]
 ['95' 17.8]
 ['71' 12.2]
 ['70' 17.0]
 ['75' 16.4]
 ['72' 13.6]
 ['102' 15.7]
 ['150' 13.2]
 ['88' 21.9]
 ['108' 15.5]
 ['120' 16.7]
 ['180' 12.1]
 ['145' 12.0]
 ['130' 15.0]
 ['150' 14.0]
 ['68' 18.5]
 ['80' 14.8]
 ['58' 18.6]
 ['96' 15.5]
 ['70' 16.8]
 ['145' 12.5]
 ['110' 19.0]
 ['145' 13.7]
 ['130' 14.9]
 ['110' 16.4]
 ['105' 16.9]
 ['100' 17.7]
 ['98' 19.0]
 ['180' 11.1]
 ['170' 11.4]
 ['190' 12.2]
 ['149' 14.5]
 ['78' 14.5]
 ['88' 16.0]
 ['75' 18.2]
 ['89' 15.8]
 ['63' 17.0]
 ['83' 15.9]
 ['67' 16.4]
 ['78' 14.1]
 ['97' 14.5]
 ['110' 12.8]
 ['110' 13.5]
 ['48' 21.5]
 ['66' 14.4]
 ['52' 19.4]
 ['70' 18.6]
 ['60' 16.4]
 ['110' 15.5]
 ['140' 13.2]
 ['139' 12.8]
 ['105' 19.2]
 ['95' 18.2]
 ['85' 15.8]
 ['88' 15.4]
 ['100' 17.2]
 ['90' 17.2]
 ['105' 15.8]
 ['85' 16.7]
 ['110' 18.7]
 ['120' 15.1]
 ['145' 13.2]
 ['165' 13.4]
 ['139' 11.2]
 ['140' 13.7]
 ['68' 16.5]
 ['95' 14.2]
 ['97' 14.7]
 ['75' 14.5]
 ['95' 14.8]
 ['105' 16.7]
 ['85' 17.6]
 ['97' 14.9]
 ['103' 15.9]
 ['125' 13.6]
 ['115' 15.7]
 ['133' 15.8]
 ['71' 14.9]
 ['68' 16.6]
 ['115' 15.4]
 ['85' 18.2]
 ['88' 17.3]
 ['90' 18.2]
 ['110' 16.6]
 ['130' 15.4]
 ['129' 13.4]
 ['138' 13.2]
 ['135' 15.2]
 ['155' 14.9]
 ['142' 14.3]
 ['125' 15.0]
 ['150' 13.0]
 ['71' 14.0]
 ['65' 15.2]
 ['80' 14.4]
 ['80' 15.0]
 ['77' 20.1]
 ['125' 17.4]
 ['71' 24.8]
 ['90' 22.2]
 ['70' 13.2]
 ['70' 14.9]
 ['65' 19.2]
 ['69' 14.7]
 ['90' 16.0]
 ['115' 11.3]
 ['115' 12.9]
 ['90' 13.2]
 ['76' 14.7]
 ['60' 18.8]
 ['70' 15.5]
 ['65' 16.4]
 ['90' 16.5]
 ['88' 18.1]
 ['90' 20.1]
 ['90' 18.7]
 ['78' 15.8]
 ['90' 15.5]
 ['75' 17.5]
 ['92' 15.0]
 ['75' 15.2]
 ['65' 17.9]
 ['105' 14.4]
 ['65' 19.2]
 ['48' 21.7]
 ['48' 23.7]
 ['67' 19.9]
 ['67' 21.8]
 ['67' 13.8]
 ['?' 17.3]
 ['67' 18.0]
 ['62' 15.3]
 ['132' 11.4]
 ['100' 12.5]
 ['88' 15.1]
 ['?' 14.3]
 ['72' 17.0]
 ['84' 15.7]
 ['84' 16.4]
 ['92' 14.4]
 ['110' 12.6]
 ['84' 12.9]
 ['58' 16.9]
 ['64' 16.4]
 ['60' 16.1]
 ['67' 17.8]
 ['65' 19.4]
 ['62' 17.3]
 ['68' 16.0]
 ['63' 14.9]
 ['65' 16.2]
 ['65' 20.7]
 ['74' 14.2]
 ['?' 15.8]
 ['75' 14.4]
 ['75' 16.8]
 ['100' 14.8]
 ['74' 18.3]
 ['80' 20.4]
 ['76' 19.6]
 ['116' 12.6]
 ['120' 13.8]
 ['110' 15.8]
 ['105' 19.0]
 ['88' 17.1]
 ['85' 16.6]
 ['88' 19.6]
 ['88' 18.6]
 ['88' 18.0]
 ['85' 16.2]
 ['84' 16.0]
 ['90' 18.0]
 ['92' 16.4]
 ['74' 15.3]
 ['68' 18.2]
 ['68' 17.6]
 ['63' 14.7]
 ['70' 17.3]
 ['88' 14.5]
 ['75' 14.5]
 ['70' 16.9]
 ['67' 15.0]
 ['67' 15.7]
 ['67' 16.2]
 ['110' 16.4]
 ['85' 17.0]
 ['92' 14.5]
 ['112' 14.7]
 ['96' 13.9]
 ['84' 13.0]
 ['90' 17.3]
 ['86' 15.6]
 ['52' 24.6]
 ['84' 11.6]
 ['79' 18.6]
 ['82' 19.4]]

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X[:, 1:3])

NameError: ignored

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

ValueError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)
print(X_train)

[[29.5 '71' 12.2]
 [23.5 '110' 12.6]
 [16.0 '150' 12.0]
 [19.2 '145' 13.2]
 [22.0 '105' 14.5]
 [44.6 '67' 13.8]
 [43.1 '48' 21.5]
 [20.0 '91' 14.0]
 [17.0 '130' 15.4]
 [28.0 '75' 16.4]
 [29.5 '68' 16.6]
 [17.0 '150' 11.5]
 [32.0 '70' 17.0]
 [32.3 '67' 17.8]
 [24.0 '92' 16.4]
 [24.0 '96' 13.5]
 [15.0 '150' 9.5]
 [14.0 '225' 10.0]
 [31.0 '67' 16.0]
 [38.1 '60' 18.8]
 [20.3 '103' 15.9]
 [36.4 '67' 19.9]
 [27.0 '88' 14.5]
 [21.0 '72' 19.5]
 [34.3 '78' 15.8]
 [32.0 '65' 21.0]
 [15.0 '100' 17.0]
 [18.0 '97' 14.5]
 [20.0 '88' 19.0]
 [21.5 '115' 15.4]
 [18.0 '95' 19.0]
 [23.0 '88' 17.0]
 [17.0 '125' 13.6]
 [17.0 '100' 15.5]
 [21.6 '115' 15.7]
 [22.3 '88' 17.3]
 [18.0 '100' 16.0]
 [22.5 '90' 17.6]
 [29.0 '84' 16.0]
 [15.0 '170' 10.0]
 [19.0 '85' 18.5]
 [25.8 '92' 14.4]
 [18.5 '150' 13.0]
 [28.4 '90' 16.0]
 [30.0 '84' 12.9]
 [15.0 '150' 12.5]
 [20.6 '110' 16.6]
 [31.6 '74' 18.3]
 [17.5 '140' 13.7]
 [46.6 '65' 17.9]
 [31.5 '68' 18.5]
 [16.0 '100' 18.0]
 [24.0 '75' 15.5]
 [23.7 '100' 12.5]
 [38.0 '67' 16.2]
 [15.5 '190' 12.2]
 [20.0 '90' 19.5]
 [30.0 '80' 14.8]
 [36.0 '70' 17.3]
 [14.0 '160' 8.0]
 [18.1 '139' 11.2]
 [16.0 '105' 18.5]
 [22.0 '98' 14.5]
 [17.5 '110' 16.4]
 [21.0 '?' 17.0]
 [19.0 '100' 16.0]
 [39.1 '58' 16.9]
 [25.0 '110' 16.4]
 [25.0 '81' 16.9]
 [34.2 '70' 13.2]
 [13.0 '140' 16.0]
 [12.0 '180' 12.5]
 [13.0 '150' 12.0]
 [20.5 '95' 18.2]
 [32.2 '75' 15.2]
 [26.0 '113' 12.5]
 [30.5 '63' 17.0]
 [15.0 '165' 11.5]
 [20.0 '100' 16.0]
 [14.0 '175' 11.5]
 [18.0 '90' 13.5]
 [20.2 '139' 12.8]
 [22.0 '112' 14.7]
 [35.0 '69' 18.0]
 [17.0 '140' 10.5]
 [12.0 '167' 12.5]
 [20.8 '85' 16.7]
 [16.0 '149' 14.5]
 [32.7 '132' 11.4]
 [13.0 '175' 13.0]
 [35.1 '60' 16.1]
 [17.5 '145' 12.5]
 [19.0 '95' 16.0]
 [13.0 '129' 12.0]
 [14.0 '220' 9.0]
 [24.3 '90' 20.1]
 [23.0 '125' 17.4]
 [16.0 '170' 11.5]
 [13.0 '130' 15.0]
 [23.0 '97' 14.5]
 [27.2 '84' 15.7]
 [19.0 '97' 13.5]
 [20.5 '105' 16.9]
 [34.0 '88' 18.0]
 [13.0 '145' 13.0]
 [15.0 '150' 13.5]
 [24.0 '95' 15.0]
 [15.5 '142' 14.3]
 [16.5 '180' 12.1]
 [27.0 '88' 14.5]
 [31.8 '65' 19.2]
 [18.5 '98' 19.0]
 [25.4 '116' 12.6]
 [18.0 '105' 16.0]
 [19.0 '88' 21.9]
 [11.0 '150' 14.0]
 [15.5 '170' 11.4]
 [15.0 '72' 21.0]
 [19.2 '125' 15.0]
 [19.0 '112' 15.5]
 [32.4 '75' 16.8]
 [20.6 '105' 15.8]
 [31.0 '52' 16.5]
 [27.5 '95' 14.2]
 [13.0 '175' 12.0]
 [21.0 '107' 14.0]
 [16.0 '110' 18.0]
 [14.0 '150' 15.5]
 [14.0 '150' 14.5]
 [23.0 '95' 16.0]
 [16.0 '100' 17.0]
 [15.0 '198' 10.0]
 [22.0 '97' 14.5]
 [26.0 '80' 16.5]
 [26.0 '69' 18.0]
 [31.0 '68' 17.6]
 [15.0 '72' 19.5]
 [15.0 '145' 13.0]
 [30.0 '68' 16.5]
 [16.2 '133' 15.8]
 [29.0 '49' 19.5]
 [26.5 '72' 13.6]
 [36.0 '75' 14.5]
 [37.0 '65' 19.4]
 [25.0 '92' 14.9]
 [30.5 '78' 14.1]
 [37.0 '68' 18.2]
 [14.0 '153' 13.5]
 [21.5 '110' 12.8]
 [12.0 '198' 11.5]
 [26.6 '84' 16.4]
 [38.0 '63' 14.7]
 [21.0 '110' 15.0]
 [41.5 '76' 14.7]
 [15.0 '190' 8.5]
 [18.0 '100' 15.5]
 [32.0 '84' 11.6]
 [18.0 '110' 13.5]
 [23.9 '90' 22.2]
 [37.3 '69' 14.7]
 [40.8 '65' 19.2]
 [44.0 '52' 24.6]
 [19.0 '88' 15.5]
 [18.0 '88' 14.5]
 [12.0 '180' 11.5]
 [26.8 '115' 12.9]
 [40.9 '?' 17.3]
 [14.0 '148' 13.5]
 [24.0 '95' 15.5]
 [20.0 '110' 13.5]
 [32.0 '61' 19.0]
 [24.0 '110' 14.0]
 [19.8 '85' 18.2]
 [16.9 '155' 14.9]
 [13.0 '170' 13.0]
 [32.9 '100' 14.8]
 [20.2 '90' 18.2]
 [23.6 '?' 14.3]
 [29.0 '70' 14.2]
 [19.4 '90' 17.2]
 [14.0 '140' 16.0]
 [26.6 '105' 19.0]
 [20.2 '88' 17.1]
 [18.0 '100' 15.0]
 [14.0 '225' 10.0]
 [29.8 '90' 15.5]
 [27.0 '90' 18.0]
 [36.0 '84' 13.0]
 [22.0 '100' 15.4]
 [24.5 '88' 16.0]
 [24.0 '90' 14.5]
 [27.0 '88' 18.6]
 [23.8 '85' 17.6]
 [26.0 '92' 14.5]
 [17.6 '129' 13.4]
 [21.0 '87' 19.5]
 [22.0 '72' 19.0]
 [34.1 '68' 16.0]
 [28.0 '90' 16.5]
 [33.7 '75' 14.4]
 [25.5 '96' 15.5]
 [34.7 '63' 14.9]
 [19.9 '110' 15.5]
 [18.0 '105' 16.5]
 [18.5 '110' 16.2]
 [34.5 '?' 15.8]
 [22.0 '94' 16.5]
 [38.0 '85' 17.0]
 [14.0 '175' 12.0]
 [13.0 '158' 13.0]
 [36.1 '66' 14.4]
 [13.0 '165' 12.0]
 [18.0 '130' 12.0]
 [11.0 '210' 13.5]
 [28.0 '88' 19.6]
 [19.4 '140' 13.2]
 [23.0 '95' 15.0]
 [17.5 '140' 13.0]
 [26.0 '75' 14.0]
 [30.0 '67' 16.4]
 [37.7 '62' 17.3]
 [35.0 '88' 15.1]
 [16.0 '150' 14.5]
 [26.0 '78' 14.5]
 [23.9 '97' 14.9]
 [23.0 '54' 23.5]
 [17.5 '95' 17.8]
 [13.0 '150' 13.2]
 [32.4 '72' 17.0]
 [24.0 '97' 15.0]
 [20.0 '122' 13.5]
 [32.1 '70' 15.5]
 [18.0 '97' 15.5]
 [15.0 '130' 14.9]
 [29.9 '65' 20.7]
 [16.0 '180' 11.1]
 [33.5 '90' 13.2]
 [27.0 '86' 15.6]
 [18.0 '105' 16.5]
 [20.0 '95' 16.5]
 [21.0 '86' 16.5]
 [28.0 '92' 17.0]
 [31.0 '82' 19.4]
 [26.0 '70' 20.5]
 [26.0 '46' 20.5]
 [14.0 '150' 11.5]
 [43.4 '48' 23.7]
 [32.8 '52' 19.4]
 [13.0 '150' 14.5]
 [19.1 '90' 18.7]
 [16.0 '105' 15.5]
 [27.4 '80' 15.0]
 [14.0 '150' 13.5]
 [20.2 '85' 15.8]
 [18.0 '112' 14.5]
 [10.0 '200' 15.0]
 [18.2 '135' 15.2]
 [13.0 '170' 12.0]
 [13.0 '175' 11.0]
 [28.0 '80' 15.0]
 [19.2 '105' 19.2]
 [26.0 '79' 17.7]
 [13.0 '130' 14.0]
 [36.1 '60' 16.4]
 [39.4 '70' 18.6]
 [29.0 '78' 14.5]
 [23.2 '105' 16.7]
 [16.0 '140' 14.0]
 [35.7 '80' 14.4]
 [23.0 '86' 14.0]
 [20.0 '102' 15.7]
 [32.0 '67' 15.7]
 [34.0 '70' 16.9]
 [25.0 '75' 17.0]
 [28.0 '90' 14.0]
 [33.5 '83' 15.9]
 [30.0 '76' 14.5]
 [22.0 '86' 16.0]
 [25.0 '95' 14.0]
 [15.0 '150' 11.0]
 [16.5 '120' 16.7]
 [34.4 '65' 16.2]
 [34.5 '70' 14.9]
 [24.5 '60' 22.1]
 [14.0 '137' 14.5]
 [44.3 '48' 21.7]
 [27.9 '105' 14.4]
 [25.1 '88' 15.4]
 [25.0 '80' 17.0]
 [19.0 '100' 13.0]
 [14.0 '165' 12.0]
 [28.1 '80' 20.4]
 [30.0 '70' 19.5]
 [22.4 '110' 15.8]
 [18.6 '110' 18.7]
 [26.0 '46' 21.0]
 [29.0 '52' 22.2]
 [29.0 '75' 16.0]
 [31.9 '71' 14.0]
 [16.0 '230' 9.5]
 [11.0 '180' 11.0]
 [36.0 '58' 18.6]
 [16.5 '138' 13.2]
 [31.3 '75' 17.5]
 [19.0 '100' 15.0]
 [13.0 '145' 12.0]
 [27.0 '90' 17.3]
 [12.0 '225' 11.0]
 [15.0 '110' 19.0]
 [17.7 '165' 13.4]
 [30.7 '76' 19.6]
 [14.0 '150' 14.0]
 [27.2 '71' 24.8]
 [25.0 '95' 17.5]
 [15.0 '150' 12.5]
 [22.0 '95' 15.5]
 [23.0 '83' 17.0]]